# Generated by Django 4.0.5 on 2022-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(default='2022-06-23 21:23:48.045145', verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='photo',
            name='update_at',
            field=models.DateTimeField(default='2022-06-23 21:23:48.045098', verbose_name='updated date'),
        ),
    ]
