# Generated by Django 4.0.5 on 2022-06-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_created_at_photo_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='updated date'),
        ),
    ]
