# Generated by Django 4.0.5 on 2022-07-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_taken',
            field=models.DateTimeField(null=True, verbose_name='date taken'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name_of_creator',
            field=models.CharField(max_length=200, null=True, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.CharField(max_length=500, null=True, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
